### ISSUE TITLE
User-made Music SR output samples

### ISSUE THREAD

**Issue by asigalov61** [haoheliu/versatile_audio_super_resolution#10]
@RetroCirce @haoheliu 

I was not sure where to post it (or if I should submit a PR,) but I figured you may be interested in adding user-made output samples to your repo somewhere to showcase real-life applications/performance of your model.

Here is the link:

https://soundcloud.com/aleksandr-sigalov-61/sets/music-super-resolution-16khz-48khz

Output samples are very nice considering the input WAVs. Your model seems to perform well on music, especially at higher frequencies like Violin frequencies. 

Let me know if its appropriate.

Sincerely,

Alex

**Comment by haoheliu** [comment]
@asigalov61 Will build a HF Space demo later - then you can share your sample at the discussion area. Alternatively you are welcomed to join this discord channel https://discord.gg/HWeBsJryaf and share your sample!

**Comment by asigalov61** [comment]
@haoheliu Ok. Thank you very much.
