### ISSUE TITLE
No change in output sample quality

### ISSUE THREAD

**Issue by JLenzy** [haoheliu/versatile_audio_super_resolution#12]
Myself and a number of friends have tried to run the basic inference script. The output file comes out with the same quality, and a bit quieter.

Is there some guidance you can provide on how to get the script to work? Perhaps a specific seed? Have tried with 100, 200 and 300 steps.

**Comment by 78Alpha** [comment]
Adding in some information for anyone looking in the future. The container in use will have 48 KHz that it can fill, but this doesn't mean it will upgrade audio to 48 KHz. It will be 24 KHz per channel. Most audio today would be 18 KHz to 22.5 KHz. The restored upper range should inaudible to people older than 24.

This tool is good at restoring badly damaged audio, such as a recording that has been crushed into 6 KHz. The audio will then have its high notes restored and not sound like an old Walkman recording.
